// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwwtvyhefvuwfpipksrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3d3R2eWhlZnZ1d2ZwaXBrc3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MTI2NjksImV4cCI6MjA2NDI4ODY2OX0.uZUup0sA6IxDqsGYU8iaD7iF1qCmuCBqRG1dygv10v0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);