
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yedytkprmsmwvqhxvmcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZHl0a3BybXNtd3ZxaHh2bWN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NTYwOTksImV4cCI6MjA2NDQzMjA5OX0.2lW_MduBsK7wO9br7goF7n1gd1IZfG6CSNsf7lQa1lY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: window?.localStorage || undefined,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
    // Extended session persistence - sessions will persist for longer periods
    storageKey: 'mgsdeal-auth-token'
  },
  global: {
    headers: {
      'X-Client-Info': 'mgsdeal-app'
    }
  },
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});
